base_lr: 0.1
batch_size: 64
config: ./config/NTU-cross-subject/train_joint_aagcn.yaml
device: 0
eval_interval: 5
feeder: feeders.feeder.Feeder
ignore_weights: []
log_interval: 100
model: model.aagcn.Model
model_args:
  graph: graph.ntu_rgb_d.Graph
  graph_args:
    labeling_mode: spatial
  num_class: 19
  num_person: 2
  num_point: 25
model_saved_name: ./runs/ntu_cs_aagcn_joint
nesterov: true
num_epoch: 50
num_worker: 32
only_train_epoch: 5
only_train_part: true
optimizer: SGD
phase: train
print_log: true
save_interval: 2
save_score: false
seed: 1
show_topk:
- 1
- 5
start_epoch: 0
step:
- 30
- 40
test_batch_size: 64
test_feeder_args:
  data_path: /home/andrea/Desktop/NTU_DATASET/pickle/NTU-RGB-D/xsub/val_data.npy
  label_path: /home/andrea/Desktop/NTU_DATASET/pickle/NTU-RGB-D/xsub/val_label.pkl
train_feeder_args:
  data_path: /home/andrea/Desktop/NTU_DATASET/pickle/NTU-RGB-D/xsub/train_data.npy
  debug: false
  label_path: /home/andrea/Desktop/NTU_DATASET/pickle/NTU-RGB-D/xsub/train_label.pkl
  normalization: false
  random_choose: false
  random_move: false
  random_shift: false
  window_size: -1
warm_up_epoch: 5
weight_decay: 0.0001
weights: null
work_dir: ./work_dir/ntu/xsub/aagcn_joint
